### ISSUE TITLE
how to bind functions to certain electrodes?

### ISSUE THREAD

**Issue by timurufa86** [r89m/MPR121Button#1]
how to bind functions to certain electrodes?
  for example concerned an electrode 1 - made the first
delayed an electrode 1 - other action

**Comment by r89m** [comment]
Hi @timurufa86,

The [examples](https://github.com/r89m/MPR121Button/blob/master/examples/BasicMPR121Button/BasicMPR121Button.ino) should hopefully tell you all you need to know.

This example shows the creation of 3 buttons targeting electrodes 1, 2 & 3. For each button you can receive an event when the button is pressed, when it has been held and when it has been released.

Let me know if you need any other help,

Richard

**Comment by timurufa86** [comment]
Hi!
yes I worked with your examples in an example "fast reading" one processor on all electrodes, and here a question - I cannot understand as by means of one processor for example of void callThisFuntionOnHold (Button & btn, uint_16t duration) to recognize what electrode was involved... in the description it is specified that "btn" - the link to the button, but how to work with this link?

**Comment by r89m** [comment]
Ah right, I understand your question now.

If, for example, you created 3 buttons:

````
...
MPR121Button button1 = MPR121Button(touchSensor, 1);
MPR121Button button2 = MPR121Button(touchSensor, 2);
MPR121Button button3 = MPR121Button(touchSensor, 3);
...
````

and defined your callback as follows:

````
void callThisFuntionOnHold(Button& btn, uint16_t duration) {
    if (btn.is(button1)) {
        // Do electrode 1 related tasks
    } else if (btn.is(button2)) {
        // Do electrode 2 related tasks
    } else if (btn.is(button3)) {
        // Do electrode 3 related tasks
    }
}
````
You would be able to perform different actions depending on which button is pressed.


Alternatively you could define 3 callback functions:
````
void callThisFuntionOnHoldButton1(Button& btn, uint16_t duration) {...}
void callThisFuntionOnHoldButton2(Button& btn, uint16_t duration) {...}
void callThisFuntionOnHoldButton3(Button& btn, uint16_t duration) {...}
````
And register the correct one with each button. 

Personally, I would use the first method.

Let me know if you need any more help

**Comment by timurufa86** [comment]
thank you very much!!! here what I looked for... 
I first used the second method. but your the first it is finite better... 
  (you would enter this method to examples (for all users))
!!!!!!!!!!!!the question is closed!!!!!!!!!!!
